# Generated by Django 2.1.2 on 2019-04-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICTapp', '0002_event_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Information',
        ),
    ]
