# Generated by Django 2.1.2 on 2019-04-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ICTapp', '0003_auto_20190403_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('purpose', models.TextField()),
                ('tasks', models.TextField()),
                ('perspectives', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='Specialty_images')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='ICTapp.Specialty'),
        ),
    ]
