# Generated by Django 2.1.2 on 2019-04-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICTapp', '0004_auto_20190407_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
