# Generated by Django 2.1.2 on 2019-04-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='full_name',
        ),
    ]
